"""Merge newly shipped sentence files into the user's Sentences folder.

The problem: users are actively invited to edit and add sentence files (there is
an "Open Sentences Folder" menu item), so an update must deliver new and
corrected content **without** ever discarding what they wrote.

Timestamps cannot decide this.  ``robocopy /XO`` looks like the answer but
cannot tell "the user edited this" from "we shipped a newer one": someone who
installs in January and edits a file in February loses that edit to a build made
in March, because the shipped file genuinely is newer.

So the question is answered from a record of what KeyQuest has ever shipped,
``sentence_history.json`` at the app root (see
``tools/dev/build_sentence_hashes.py``).  A file whose content matches **any**
version we ever shipped was not written by the user:

=================================  ============================================
Situation                          Outcome
=================================  ============================================
Not in the user's folder           Copied in.  New content arrives.
Matches a hash we ever shipped     Not theirs, so it is updated.
Matches nothing we shipped         They wrote it.  Kept, untouched.
Name we have never shipped         Their own file.  Never considered.
No history available               Nothing is replaced.  Conservative.
=================================  ============================================

Matching *any* historical version, rather than only the previous release, is
what makes this work on a real install.  An earlier design kept a copy of the
last release's files as a baseline, and it froze: an install that had no
baseline yet had to keep everything, the baseline then advanced past those
files, and they were treated as customized forever after.  A file skipped once
because it was locked froze the same way.  Both disappear when "unmodified" is a
property of the content rather than of one particular previous release.

The merge runs here, in Python at startup, rather than in the update ``.bat``.
Batch cannot hash and compare without awkward ``certutil`` work, and doing it
here means it is unit-testable and behaves identically for the installer and
portable layouts.

Deliberately dependency-free (no pygame, no audio, no speech) so it can be
tested directly.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path


SENTENCES_DIR_NAME = "Sentences"
# Where the updater drops the incoming release's sentence files.  Transient: it
# exists only between an update being applied and the next startup.
INCOMING_DIR_NAME = "_sentences_incoming"
# Every hash KeyQuest has ever shipped for each file name, shipped at the app
# root and regenerated by tools/dev/build_sentence_hashes.py.
HISTORY_FILE_NAME = "sentence_history.json"
# A pristine copy of the files this release ships, packaged with the app.  Two
# jobs: it is what "Restore default sentence files" restores FROM, and it lets
# the merge work even if an update could not stage anything.  The user is never
# expected to look in here and nothing ever writes to it.
DEFAULTS_DIR_PARTS = ("defaults", "Sentences")
# Remembers which shipped files this install has had, so a file the user
# DELETES stays deleted instead of reappearing on the next update.  Deleting is
# a way of saying "I do not want this", and re-adding it silently overrides
# that.  Lives beside the app and is excluded from the updater's mirror.
PREFS_FILE_NAME = "sentence_prefs.json"
# An earlier design kept a duplicate of the last release's files here.  The
# history file makes it unnecessary, and it was a second copy of every sentence
# file sitting in the app folder.  Removed on sight.
_OBSOLETE_BASELINE_DIR = "_sentences_shipped"

_MERGEABLE_SUFFIXES = {".txt", ".json"}


@dataclass
class MergeResult:
    """What the merge did, in terms a caller can report to the user."""

    added: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    kept_customized: list[str] = field(default_factory=list)
    # Shipped files the user removed on purpose. Not re-added, and deliberately
    # not announced: they know, they did it, and hearing about it after every
    # update would be nagging.
    respected_deletions: list[str] = field(default_factory=list)
    ran: bool = False

    @property
    def changed(self) -> bool:
        return bool(self.added or self.updated)

    def announcement(self) -> str:
        """A spoken summary, or an empty string when there is nothing to say.

        Deliberately plain ASCII with no symbols: this is read aloud.
        """
        parts: list[str] = []
        if self.added:
            count = len(self.added)
            parts.append(f"{count} new sentence {'file' if count == 1 else 'files'} added")
        if self.updated:
            count = len(self.updated)
            parts.append(f"{count} sentence {'file' if count == 1 else 'files'} updated")
        if self.kept_customized:
            count = len(self.kept_customized)
            parts.append(
                f"{count} of your own sentence {'file was' if count == 1 else 'files were'} left unchanged"
            )
        if not parts:
            return ""
        body = parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + ", and " + parts[-1]
        # Only claim content changed when it actually did.  A kept-only result
        # means nothing was added or updated, so "Sentence content updated"
        # would be a plain falsehood, and the user cannot look to check.
        lead = "Sentence content updated." if self.changed else "Sentence content checked."
        return f"{lead} {body[0].upper()}{body[1:]}."


def _read(path: Path) -> bytes | None:
    try:
        return path.read_bytes()
    except OSError:
        return None


def content_hash(path: Path) -> str | None:
    """SHA-256 of *path* with line endings normalised, or None if unreadable.

    Must stay in step with ``content_hash`` in
    ``tools/dev/build_sentence_hashes.py``.  They are the same function on
    purpose: a divergence would make every user's files look edited and silently
    stop all corrections. ``tests/test_sentence_merge.py`` guards this by
    checking the repo's own files against the shipped history.

    Line endings are normalised because an editor that rewrites CRLF as LF has
    not meaningfully changed the file, and that user should still get fixes.
    """
    data = _read(path)
    if data is None:
        return None
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def load_shipped_history(app_dir: Path) -> dict[str, set[str]]:
    """Load every hash ever shipped, keyed by file name.

    An empty mapping on any problem: a missing or corrupt history file must
    never authorise replacing something, it must only make the merge cautious.
    """
    try:
        loaded = json.loads((app_dir / HISTORY_FILE_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(loaded, dict):
        return {}
    return {
        str(name): {str(h) for h in hashes}
        for name, hashes in loaded.items()
        if isinstance(hashes, list)
    }


def _load_prefs(root: Path) -> dict:
    try:
        loaded = json.loads((root / PREFS_FILE_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _save_prefs(root: Path, prefs: dict) -> None:
    try:
        (root / PREFS_FILE_NAME).write_text(
            json.dumps(prefs, indent=2, sort_keys=True), encoding="utf-8"
        )
    except OSError:
        pass  # losing the record is bad, but never worth failing startup over


def _string_set(prefs: dict, key: str) -> set[str]:
    value = prefs.get(key)
    return {str(v) for v in value} if isinstance(value, list) else set()


def defaults_dir(root: Path) -> Path:
    return root.joinpath(*DEFAULTS_DIR_PARTS)


def update_deletion_record(app_dir: str | Path) -> set[str]:
    """Notice files the user has deleted, and remember them.

    Runs every startup rather than only at update time, so a deletion is
    recorded promptly instead of depending on when the next release lands.  A
    name is only counted as deleted once we have seen this install actually have
    it; otherwise a file that simply never arrived would look deleted.
    """
    root = Path(app_dir)
    sentences = root / SENTENCES_DIR_NAME
    prefs = _load_prefs(root)
    seen = _string_set(prefs, "seen")
    deleted = _string_set(prefs, "deleted")

    present = {p.name for p in _mergeable_files(sentences)}
    shipped_names = {p.name for p in _mergeable_files(defaults_dir(root))}

    # Anything shipped that this install has, we have now seen.
    seen |= present & shipped_names
    # Anything we had seen and that has since gone was removed by the user.
    deleted |= (seen - present) & shipped_names
    # And anything that is back was clearly wanted after all.
    deleted -= present

    prefs["seen"] = sorted(seen)
    prefs["deleted"] = sorted(deleted)
    _save_prefs(root, prefs)
    return deleted


def list_default_sentences(app_dir: str | Path) -> list[str]:
    """Names of the sentence files this release ships, for a caller to report."""
    return [p.name for p in _mergeable_files(defaults_dir(Path(app_dir)))]


def restore_default_sentences(app_dir: str | Path) -> tuple[list[str], list[str]]:
    """Put every shipped sentence file back as it was released.

    Returns ``(restored, failed)`` by file name.  Files the user created
    themselves are never touched: they are not part of the shipped set, so there
    is nothing to restore them to.  Also clears the deletion record, since
    restoring is an explicit request for the defaults back.
    """
    root = Path(app_dir)
    sentences = root / SENTENCES_DIR_NAME
    restored: list[str] = []
    failed: list[str] = []
    try:
        sentences.mkdir(parents=True, exist_ok=True)
        for source in _mergeable_files(defaults_dir(root)):
            try:
                shutil.copy2(source, sentences / source.name)
                restored.append(source.name)
            except OSError:
                failed.append(source.name)

        prefs = _load_prefs(root)
        prefs["deleted"] = []
        prefs["seen"] = sorted(_string_set(prefs, "seen") | set(restored))
        _save_prefs(root, prefs)
    except Exception:
        pass
    return restored, failed


def _mergeable_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(
        p for p in directory.iterdir()
        if p.is_file() and p.suffix.lower() in _MERGEABLE_SUFFIXES
    )


def merge_sentences(app_dir: str | Path) -> MergeResult:
    """Merge any incoming shipped sentence files into the user's folder.

    Safe to call on every startup; does nothing when no update has staged
    anything.  Never raises: failing to merge must not stop the app launching.
    """
    result = MergeResult()
    try:
        root = Path(app_dir)
        sentences = root / SENTENCES_DIR_NAME
        incoming = root / INCOMING_DIR_NAME

        obsolete = root / _OBSOLETE_BASELINE_DIR
        if obsolete.is_dir():
            shutil.rmtree(obsolete, ignore_errors=True)

        # Record deletions before deciding anything, so a file removed since the
        # last launch is respected by this merge rather than the next one.
        deleted = update_deletion_record(root)

        # Fall back to the shipped defaults when nothing was staged: they are
        # the current release's content either way, so the merge still works if
        # an update could not stage.
        source_dir = incoming if incoming.is_dir() else defaults_dir(root)
        if not source_dir.is_dir():
            return result
        incoming = source_dir

        result.ran = True
        sentences.mkdir(parents=True, exist_ok=True)
        # The incoming release's history is preferred: it is the newest and most
        # complete record, and it is what lets an install that has never seen
        # this feature still receive corrections to files it never edited.
        history = load_shipped_history(incoming) or load_shipped_history(root)

        applied_every_file = True
        for incoming_file in _mergeable_files(incoming):
            name = incoming_file.name
            live = sentences / name
            known = history.get(name)
            try:
                if name in deleted:
                    # Deleting is how someone says "I do not want this topic".
                    # Re-adding it every update overrides that, and it comes
                    # back in the menus too.
                    result.respected_deletions.append(name)
                elif not live.exists():
                    shutil.copy2(incoming_file, live)
                    result.added.append(name)
                elif known and content_hash(live) in known:
                    shutil.copy2(incoming_file, live)
                    result.updated.append(name)
                else:
                    # Either they edited it, or we have no record proving they
                    # did not.  Both mean: leave it alone.
                    result.kept_customized.append(name)
            except OSError:
                # One locked or unreadable file must not abandon the rest, and
                # must not quietly count as done.
                applied_every_file = False
                continue

        # Only consume the staged set once every file was dealt with.  Leaving
        # it in place means the next startup retries, instead of a transient
        # lock costing the user that correction permanently.
        if applied_every_file and incoming == root / INCOMING_DIR_NAME:
            shutil.rmtree(incoming, ignore_errors=True)

        return result
    except Exception:
        return result
